// calling in express to use its methods and functionality
const express = require('express');

// call in our functions from the controller
const {getBanks, getBank, createBank, updateBank, deleteBank} = require('../controllers/bankController.js');

// set up our router instance
const router = express.Router();

// define our routes/endpoints
// to get all banks, we don't need to pass through the specific id of that bank
router.get('/getBanks', getBanks);
// to get a specific bank, we pass through that banks ID
router.get('/getBank/:id', getBank);
// when creating a bank, we don't need to pass through a specific ID either, as it is autogenerated
router.post('/createBank', createBank);
// when updating a bank, we want to update a SPECIFIC one, so we specify the ID
router.put('/:id', updateBank);
// when deleting we also pass an ID
router.delete('/deleteBank/:id', deleteBank);
// finally we export our routes
module.exports = router;