// calling in express to use its methods and functionality
const express = require('express');

// call in our functions from the controller
const { getTransaction, getTransactions, createTransaction, updateStatus} = require('../controllers/transactionController.js');

// set up our router instance
const router = express.Router();

// define our routes/endpoints
router.get('/getTransactions', getTransactions);
// to get a specific transaction, we pass through that transactions ID
router.get('/:id', getTransaction);
// when creating a transaction, we don't need to pass through a specific ID either, as it is autogenerated
router.post('/createTransaction', createTransaction);
// (verifying the swift code)
// when updating a transaction, we want to update a SPECIFIC one, so we specify the ID
router.put('/:id', updateStatus);

// finally we export our routes
module.exports = router;